language: go

go:
    - 1.4

addons:
    postgresql: "9.3"

before_script: 
  - psql -U postgres -c "create extension postgis"
  - ./database/scripts/initdb-93.sh
  - ./haz-wfs-consumer/scripts/initdb-93.sh

install:
# Add Godeps dependencies to GOPATH and PATH
  - export GOPATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace:$GOPATH"
  - export PATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace/bin:$PATH"

script: go test ./...  
