language: go
go:
- 1.6.1
install: true
addons:
  postgresql: '9.4'
before_script:
- psql -U postgres -c "create extension postgis"
- ./database/scripts/initdb-93.sh
script: 
- export $(cat geonet-rest/env.list | grep = | xargs) && go test ./geonet-rest  -v
- export $(cat msg/env.list | grep = | xargs) && go test ./msg  -v
notifications:
  hipchat:
    rooms:
      secure: Bu3Ic6nQABzKPhLeQRnxbvrQ5l+bDMdSVWmTTU65BKEFrMQJrC5SJfM1Bw1cCjnVafwSgIqQPPfT+AiLalJJoLBUah+w3rIs50Smpf7dwN2RTsLSBKwyYWqjbnPwJ9irI3Z3HNJmJ6LeumogWAjgzl0nll3b32aauF8wMO7N3pZ9tI7qG6RZFJCioQzXIyK+gA/p03P9/HYvUvYh/R86AcODpn7NGTtxwHmGQFe7SjJrRcin71ZJiXW3xGhLsWxbru6ktSn+cbKGW+HGVgF8lSLFLgC5veYiY6Rmdob7KI6NBelCR3CcwD3mGn//3qn1Kjo/y94yoS/bKbkiB61puXN03rqDlZFgLp6BXJcQQJZPc05P0WxQyKX3m5W0G2DB3gr4DgFSg0UzvZsujNPxc/VF2cO0DNtv3OS/SPaWi88/VCg2wqehj7QuXZbeyRiKdL2pgR/9k6TWvkZOK2JJTYXR+AOWPKUnGyRh64OSrd5UKu2C3Su4Ph1zA9wolO35KuZT0aHS7dcp4I7QhAbMzDWczj8nY0sOL5nn+g3pY2llqpjhfHbb2SIbp5XvI5135ipDAwl1MMckT4OKx+CvjlaEyqqX/EHLv7jJ/q5YTC1ph+QeQ+6xanBiwvA231eQujDLKRmLCFbWbAB66JWyGcjjy9AJiTI3X9dMMBNegfA=
    notify: true
    on_success: always
    on_failure: always
    