sudo: required

language: go
go:
- 1.7
services:
  - docker

before_deploy:
  - docker login --email="." --username="geonet+dockerbuild" --password="$docker_password" quay.io

# trying to fix postgis bug which comes on the travis infrastructure that has sudo.
before_install:
 - export DEBIAN_FRONTEND=noninteractive;
   sudo -E apt-get -yq update &>> ~/apt-get-update.log;
   sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install postgresql-9.4-postgis-2.2
 - sudo apt-get install -y xsltproc

install: true
addons:
  postgresql: '9.4'
before_script:
- psql -U postgres -c "create extension postgis"
- ./database/scripts/initdb-93.sh
script: 
- ./all.sh

notifications:
  hipchat:
    rooms:
      secure: Bu3Ic6nQABzKPhLeQRnxbvrQ5l+bDMdSVWmTTU65BKEFrMQJrC5SJfM1Bw1cCjnVafwSgIqQPPfT+AiLalJJoLBUah+w3rIs50Smpf7dwN2RTsLSBKwyYWqjbnPwJ9irI3Z3HNJmJ6LeumogWAjgzl0nll3b32aauF8wMO7N3pZ9tI7qG6RZFJCioQzXIyK+gA/p03P9/HYvUvYh/R86AcODpn7NGTtxwHmGQFe7SjJrRcin71ZJiXW3xGhLsWxbru6ktSn+cbKGW+HGVgF8lSLFLgC5veYiY6Rmdob7KI6NBelCR3CcwD3mGn//3qn1Kjo/y94yoS/bKbkiB61puXN03rqDlZFgLp6BXJcQQJZPc05P0WxQyKX3m5W0G2DB3gr4DgFSg0UzvZsujNPxc/VF2cO0DNtv3OS/SPaWi88/VCg2wqehj7QuXZbeyRiKdL2pgR/9k6TWvkZOK2JJTYXR+AOWPKUnGyRh64OSrd5UKu2C3Su4Ph1zA9wolO35KuZT0aHS7dcp4I7QhAbMzDWczj8nY0sOL5nn+g3pY2llqpjhfHbb2SIbp5XvI5135ipDAwl1MMckT4OKx+CvjlaEyqqX/EHLv7jJ/q5YTC1ph+QeQ+6xanBiwvA231eQujDLKRmLCFbWbAB66JWyGcjjy9AJiTI3X9dMMBNegfA=
    notify: true
    on_success: always
    on_failure: always

deploy:
   - provider: script
     skip_cleanup: true
     script: ./build-push.sh haz-twitter-consumer haz-duty-consumer haz-ua-consumer haz-pim-consumer haz-eqnews-consumer haz-db-consumer haz-db-origin-consumer impact-intensity-consumer geonet-rest sc3ml-to-quakeml wfs quakesearch
     on: 
       branch: master 
 
env:
    global:
         - secure: lzlbM60dyckStCeFSmwrK/C80Tx0u6HyROjqzNCHFzidJk9qEDBlK6H1qEav3xMgjCIbxnZgJp+3u1cyH7KzI2+mDqf83GI+uVobMX0dD9qcG7HAYbR8DVG1ZwoCIW8aUYVs2cA0Qq0SUwvVaBntOljT6ZeBg91JVhmLZN7SeTZMRmSY/+XjLJ5RMn9frhsxNUyfPYhZa1NSAEMncUx9EtoK0PRf/+b3ldYROBEMYw7t1X9hE7s5vV2RMAJJentWZbRtcvRxB/TeYaQH1a1/jdrZrJ84CJhqToaZbNXdTZoVWY0u/d0+ANNPrW7oY9t8X6kXS8Q4luly/LDpaaRx1pv3m3P1FrTXUZ9sRhw0Y++gc+PkBSFeysK9R4Qm1e7KD4SMYbcjDFNoJ6buv7FwgdwRgTQefWs62nVpGJThVBJr53qnOFzrXhgvZ9F9U7SeD2RoCOEW5KjMC8yzk06kQs14BY96WPpbK+o1j2JqexBstTeXy2uhA/SzEfTg6yuuX9bg0S00JpUvZnhTFweK0kg0vUjqG2LjEL0OQ7AQmL7hRId7Vpi9A3rpyYw9fzGu3sO82tsOq5ZDKwFnxX4yPcofyDmYuPoXeeLTqqSi+K5t+5Thkr/xMA1/bAVZPRH+5V2K/DDXN65zGqBqzsyU8Vt5gUdQwfBMQvq5ukbYD/k=
